# Generated by Django 4.2.7 on 2023-12-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0002_fooditems_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='uname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
