# Generated by Django 4.2.7 on 2023-12-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesTracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
