# Generated by Django 4.2.7 on 2024-01-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesTracker', '0002_dailyfoodtake'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfoodtake',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
