# Generated by Django 4.2.7 on 2024-01-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesTracker', '0003_dailyfoodtake_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyfoodtake',
            name='calories',
        ),
    ]
