# Generated by Django 4.2.7 on 2023-12-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0003_alter_fooditems_uname'),
        ('caloriesTracker', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listfooditems',
            name='List',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fooditems.fooditems'),
        ),
    ]
